version: '3.8'

services:
    db:
        image: postgres
        restart: always
        container_name: 'password_manager_db'
        environment: 
            POSTGRES_PASSWORD: admin
        ports: 
            - '5432:5432'
